### ISSUE TITLE
Tests do not pass when executed inside Docker containers

### ISSUE THREAD

**Issue by cirochang** [OpenLEADR/openleadr-python#30]
I tried to run the tests on docker containers using the follow docker images: `python:3.6`, `python:3.7`, `python:3.8`. I ran the tests following the `readme.md` instructions.

For python 3.6, I got this error:
```
AttributeError: module 'asyncio' has no attribute 'create_task'
```

So it seems the error is related to a specific method of `aiohttp` that doesn't work with python 3.6.
https://stackoverflow.com/questions/53247533/attributeerror-module-asyncio-has-no-attribute-create-task
I suppose that these tests were not written using python 3.6. 

Then I tried to bump python version image.
For python 3.7 and 3.8 worked fine, but I got a different error:
```
OSError: [Errno 99] error while attempting to bind on address ('::1', 8001, 0, 0): cannot assign requested address
```

I found a similar problem here:
https://github.com/ray-project/ray/issues/7084
It seems to be a bug with aiohttp + docker. It seems like hostname '::1' or 'localhost' are not recognized. So, I tried to change the following code to this:
```python3.7
@pytest.fixture
async def start_server():
    server = OpenADRServer(vtn_id=VTN_ID)
    server.add_handler('on_create_party_registration', _on_create_party_registration)

    runner = web.AppRunner(server.app)
    await runner.setup()
    # site = web.TCPSite(runner, 'localhost', SERVER_PORT)
    site = web.TCPSite(runner, '127.0.0,1', SERVER_PORT)
    await site.start()
    yield
    await runner.cleanup()
```
As you can see I changed `localhost` => `127.0.0.1`. After that, all tests passed fine.

**Comment by stan-janssen** [comment]
Thanks for the report. I don't work with Docker myself, so these reports are valuable to me.

- I've fixed the binding to `localhost` to use `127.0.0.1` instead in that test fixture (commit a877013d0c0b83163e62a523f544e7e018f0b467)
- I assume this only affects binding to a port, and not connecting to an address on `localhost`, since we still use that extensively in the test suite.
- It seems like Docker points localhost to `::1`, but that doesn't exist. Is this correct?
- Is there a specific reason to still use Python 3.6 that I should know about?

Thanks!

**Comment by cirochang** [comment]
> * It seems like Docker points localhost to `::1`, but that doesn't exist. Is this correct?
Yes, it seems that localhost is resolving to ::1 (IPv6) but the container does not contain IPv6 support enabled.

> * Is there a specific reason to still use Python 3.6 that I should know about?
No, I was just trying to guess which Python version you have used to develop this library.

Thank you!

**Comment by stan-janssen** [comment]
All right, thanks for the info. I'm testing OpenLEADR against python 3.7, 3.8 and 3.9. You can keep an eye on the [GitHub Actions](https://github.com/OpenLEADR/openleadr-python/actions) to see the status on these three python versions.

If there's anything else Docker-related that you run in to, or something that could be improved to make your life easier, I'd be happy to hear from you.
